<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DiagnosticTestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $test = [
            ['category' => 'Tests', 'name' => 'WBC/DIFFERIENTIAL', 'price_in_naira' => '1200', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'DIFFERENTIAL', 'price_in_naira' => '700', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'FULL BLOOD COUNT', 'price_in_naira' => '2000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'HAEMOGLOBIN', 'price_in_naira' => '600', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'PCV', 'price_in_naira' => '500', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'BLOOD GROUP', 'price_in_naira' => '900', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'GENOTYPE', 'price_in_naira' => '1000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'ESR', 'price_in_naira' => '1200', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'RED CELL COUNT', 'price_in_naira' => '900', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'RETICS COUNT', 'price_in_naira' => '900', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'PLATELET COUNT', 'price_in_naira' => '1200', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'BLEEDING TIMEL', 'price_in_naira' => '1200', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'CLOTHING TIME', 'price_in_naira' => '1200', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'PROTHROMBIN TIME', 'price_in_naira' => '1800', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'RED CELL FRAGILITY', 'price_in_naira' => '1200', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'SICKLE CELL SCREENING', 'price_in_naira' => '2400', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'COOMBS TEST: DIRECT', 'price_in_naira' => '1200', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'COOMBS TEST: INDIRECT', 'price_in_naira' => '1500', 'created_at'=> now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'URINE: ANALYSIS', 'price_in_naira' => '900', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'URINE: MCS', 'price_in_naira' => '2000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'STOOL: ANALYSIS', 'price_in_naira' => '1000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'SPUTUM MCS', 'price_in_naira' => '3000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'SPUTUM : AFB *3CUPS', 'price_in_naira' => '5000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'SWAB: EYE', 'price_in_naira' => '2000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'SWAB: EAR', 'price_in_naira' => '2000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'SWAB: WOUND', 'price_in_naira' => '2000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'SWAB: VAGINA', 'price_in_naira' => '2000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'SWAB: URETHRAL', 'price_in_naira' => '2500', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'SEMEN ANALYSIS', 'price_in_naira' => '2500', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'SEMEN: MCS', 'price_in_naira' => '3500', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'SKIN MICROFILARIA', 'price_in_naira' => '1200', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'SKIN :MANTOUX', 'price_in_naira' => '1200', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'SKIN :SCRAPPING FOR FUNGI', 'price_in_naira' => '1500', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'BLOOD CULTURE', 'price_in_naira' => '4000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'BLOOD CULTURE: OCCULT BLOOD', 'price_in_naira' => '4000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'BLOOD CULTURE: ASO TITRE', 'price_in_naira' => '3500', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'HEPATITIS A', 'price_in_naira' => '2500', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'HEPATITIS B', 'price_in_naira' => '1800', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'HEPATITIS C', 'price_in_naira' => '2500', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'PREGNANCY TEST', 'price_in_naira' => '1000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'PREGNANCY TEST: URINE', 'price_in_naira' => '800', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'RHEUMATOID FACTOR', 'price_in_naira' => '2500', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'MALARIA TEST', 'price_in_naira' => '900', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'WIDAL TEST', 'price_in_naira' => '900', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'VDRL', 'price_in_naira' => '1500', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'HIV', 'price_in_naira' => '2000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'LEISHMANANIA', 'price_in_naira' => '1000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'SCHISTOSOME', 'price_in_naira' => '1000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'TRYPANOSOME', 'price_in_naira' => '1200', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'MICROFILARIA', 'price_in_naira' => '1200', 'created_at'=> now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'T.P.H.A', 'price_in_naira' => '1200', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'SERUM TUBERCULOSIS', 'price_in_naira' => '2000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'FASTING BLOOD SUGAR', 'price_in_naira' => '1200', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'RANDOM BLOOD SUGAR', 'price_in_naira' => '1200', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'ESTIMATED GFR', 'price_in_naira' => '5500', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'ACID PHOSPHATE', 'price_in_naira' => '2000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'ALBUMIN', 'price_in_naira' => '2000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'ALKALINE PHOSPHATASE', 'price_in_naira' => '2000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'AMYLASE', 'price_in_naira' => '2500', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'BICARBONATE', 'price_in_naira' => '2000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'BILIRUBIN TOTAL', 'price_in_naira' => '2000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'BILIRUBIN: CONJUGATED', 'price_in_naira' => '2000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'CALCIUM', 'price_in_naira' => '2000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'CREATININE', 'price_in_naira' => '2000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'CREATININE CLEARANCE', 'price_in_naira' => '2500', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'CHLORIDE', 'price_in_naira' => '2000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'TOTAL CHOLESTEROL', 'price_in_naira' => '1800', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'TOTAL :PROTEIN', 'price_in_naira' => '5000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'ELECTROLYTE', 'price_in_naira' => '4000', 'created_at'=> now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'GAMMA GLUTAMINE', 'price_in_naira' => '2000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'C.S.F', 'price_in_naira' => '2000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'LDH', 'price_in_naira' => '2500', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'SGOT', 'price_in_naira' => '1500', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'SGPT', 'price_in_naira' => '1500', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'SODIUM', 'price_in_naira' => '2000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'ORAL GLUCOSE TOLERANCE TEST', 'price_in_naira' => '5000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'TOTAL LIPIDS', 'price_in_naira' => '2000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'TRIGLYCERIDE', 'price_in_naira' => '2000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'UREA', 'price_in_naira' => '2000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'URIC ACID', 'price_in_naira' => '2000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'LIPID PROFILE', 'price_in_naira' => '5500', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'LIVER FUNCTION TEST', 'price_in_naira' => '6000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'ELECTROLYTE UREA CREATININE', 'price_in_naira' => '6000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'PHOSPHORUS', 'price_in_naira' => '2000', 'created_at'=> now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'MAGNESIUM', 'price_in_naira' => '2500', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'GLUBULIN', 'price_in_naira' => '1500', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'H.PYLORI STOOL', 'price_in_naira' => '5000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'H.PYLORI :BLOOD', 'price_in_naira' => '5000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'PROGESTERONE', 'price_in_naira' => '6000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'PROLACTIN', 'price_in_naira' => '6000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'LH', 'price_in_naira' => '6000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'TESTOSTERONE', 'price_in_naira' => '6000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'FSH', 'price_in_naira' => '6000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'T3', 'price_in_naira' => '5000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'T4', 'price_in_naira' => '5000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'TSH', 'price_in_naira' => '6000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'E2', 'price_in_naira' => '6000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'CORTISOL', 'price_in_naira' => '6000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'TYROID SCREENING', 'price_in_naira' => '15000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'MENSTRAL DISORDER', 'price_in_naira' => '22000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'HORMONAL DISORDERL', 'price_in_naira' => '22000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'OVULATION PROFILE', 'price_in_naira' => '22000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'AMH', 'price_in_naira' => '12000', 'created_at'=> now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'DHEAS', 'price_in_naira' => '10000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'HBA1C', 'price_in_naira' => '6000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'PSA', 'price_in_naira' => '12000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'LIQUID BASED CYTOLOGY', 'price_in_naira' => '10000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'BHCG', 'price_in_naira' => '5000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'ENDOMETRIAL FLUID MCS', 'price_in_naira' => '7000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'INTERUTERINE FIBROID', 'price_in_naira' => '7000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'ENDOMETRIAL POLYPS', 'price_in_naira' => '7000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Tests', 'name' => 'CHROMOSONAL ANALYSIS/HISTOLOGY', 'price_in_naira' => '130000', 'created_at' => now(), 'updated_at' => now()],


            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => '17-OH Progesterone', 'price_in_naira' => '24000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => '25-OH Vitamin D', 'price_in_naira' => '17000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Alpha Feto Protein', 'price_in_naira' => '6000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Serum Ferritin', 'price_in_naira' => '6000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Anti CCP Antibody', 'price_in_naira' => '25000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Anti-Double stranded DNA', 'price_in_naira' => '14500', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Anti-HBc', 'price_in_naira' => '6000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Anti-HBe', 'price_in_naira' => '15000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Antinuclear Antibody', 'price_in_naira' => '9000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Anti-Phospholipid IgG, IgM', 'price_in_naira' => '25000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Anti-Thyroid antibodies', 'price_in_naira' => '25000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Myoglobin', 'price_in_naira' => '4000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Beta-2 Glycoprotein IgM + IgG', 'price_in_naira' => '22000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Beta-2 Microglobulin', 'price_in_naira' => '14000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Cancer Antigen 125 (Ovary)', 'price_in_naira' => '10000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Cancer Antigen 15-3 (Breast)', 'price_in_naira' => '10000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Cancer Antigen 19-9 (GIT, Pancreas)', 'price_in_naira' => '10000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Cardiolipin (IgG + IgM)', 'price_in_naira' => '20000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'CEA (GIT,Lung,Breast)', 'price_in_naira' => '10000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Cortisol', 'price_in_naira' => '5000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'C-peptide', 'price_in_naira' => '20000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Cytomegalovirus IgG', 'price_in_naira' => '7500', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Cytomegalovirus IgM', 'price_in_naira' => '7500', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'D-Dimer', 'price_in_naira' => '6000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'DHEAS', 'price_in_naira' => '7000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Estriol', 'price_in_naira' => '12000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Ferritin', 'price_in_naira' => '6000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Growth Hormone', 'price_in_naira' => '11000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'HBeAg', 'price_in_naira' => '15000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Hepatitis A testing', 'price_in_naira' => '5000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Hepatitis B Core Antibody', 'price_in_naira' => '6000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Hepatitis B e Antibody', 'price_in_naira' => '15000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Hepatitis B e Antigen', 'price_in_naira' => '15000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Hepatitis B Surface Antibody', 'price_in_naira' => '7500', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Hepatitis B Surface Antigen', 'price_in_naira' => '5000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Hepatitis C Antibody', 'price_in_naira' => '10000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Hepatitis Screening Panel', 'price_in_naira' => '20000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Herpes Simplex Virus 1/2 IgG', 'price_in_naira' => '18000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Herpes Simplex Virus 1/2 IgM', 'price_in_naira' => '18000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'HIV Ab/Ag Combo', 'price_in_naira' => '12000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'HTVL 1+2', 'price_in_naira' => '15000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Myoglobin', 'price_in_naira' => '4000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Parathyroid Hormone', 'price_in_naira' => '7000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Pro BNP', 'price_in_naira' => '60000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Rubella IgG', 'price_in_naira' => '6000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Rubella IgM', 'price_in_naira' => '8000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Sex hormone binding globulin', 'price_in_naira' => '22000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Tacrolimus', 'price_in_naira' => '15000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Testosterone Free', 'price_in_naira' => '16000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Thyroglobulin', 'price_in_naira' => '20000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Thyroid peroxidase', 'price_in_naira' => '12000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Troponin I', 'price_in_naira' => '5000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Total Testosterone', 'price_in_naira' => '5000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Toxoplasma IgG', 'price_in_naira' => '8000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Toxoplasma IgM', 'price_in_naira' => '8000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Tumor Markers (CEA + CA 125)', 'price_in_naira' => '18000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'ENDOCRINOLOGY:Special Examination Test', 'name' => 'Vitamin B12', 'price_in_naira' => '14000', 'created_at' => now(), 'updated_at' => now()],


            ['category' => 'Special Examination', 'name' => 'HSG', 'price_in_naira' => '15000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Special Examination', 'name' => 'BARIUM SWALLOW', 'price_in_naira' => '18000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Special Examination', 'name' => 'BARIUM MEAL *FOLLOW THROUGH', 'price_in_naira' => '25000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Special Examination', 'name' => 'I.V.U', 'price_in_naira' => '27000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Special Examination', 'name' => 'BARIUM ENEMA', 'price_in_naira' => '27000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Special Examination', 'name' => 'CYSTOURETHROGRAM', 'price_in_naira' => '25000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Special Examination', 'name' => 'FISTULOGRAM', 'price_in_naira' => '15000', 'created_at' => now(), 'updated_at' => now()],


            ['category' => 'Ultrasound Scan', 'name' => 'OBSTETRICS/PELVIC', 'price_in_naira' => '2000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Ultrasound Scan', 'name' => 'ABDOMINAL', 'price_in_naira' => '3500', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Ultrasound Scan', 'name' => 'ABDOMINO-PELVIC', 'price_in_naira' => '4000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Ultrasound Scan', 'name' => 'TVS', 'price_in_naira' => '5000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Ultrasound Scan', 'name' => 'BREAST', 'price_in_naira' => '8000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Ultrasound Scan', 'name' => 'PROSTATE', 'price_in_naira' => '7000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Ultrasound Scan', 'name' => 'SCROTUM/TESTIS', 'price_in_naira' => '8000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Ultrasound Scan', 'name' => 'OCULAR/EY', 'price_in_naira' => '8000', 'created_at' => now(), 'updated_at' => now()],
            ['category' => 'Ultrasound Scan', 'name' => 'THYROIDS', 'price_in_naira' => '6000', 'created_at' => now(), 'updated_at' => now()],
        ];

        DB::table('diagnostic_tests')->insert($test);
    }
}
